using System.Collections.Generic;

namespace HWM.Parser.Mappers
{
    public static class CreatureMapper
    {
        private static IDictionary<string, string> CreatureMap = new Dictionary<string, string>()
        {
            { "dgolemup", "Могильные големы" },
            { "golddragon", "Золотые драконы" },
            { "piratemonsterup", "Пираты Ктулху" },
            { "zhryak", "Адские жнецы" },
            { "pharaoh", "Мумии фараонов" },
            { "blacktroll", "Черные тролли" },
            { "deadknight", "Рыцари смерти" },
            { "efreetisultan", "Ифриты султаны" },
            { "naga", "Наги" },
            { "magicel", "Магические элементали" },
            { "whitetiger", "Белые тигры" },
            { "dgolem", "Големы смерти" },
            { "mummy", "Мумии" },
            { "piratemonster", "Морские дьяволы" },
            { "priestessup", "Ведьмы моря" },
            { "giantarch", "Великаны-лучники" },
            { "cursedent", "Проклятые энты" },
            { "rapukk", "Рогатые жнецы" },
            { "troll", "Тролли" },
            { "giant", "Великаны" },
            { "efreeti", "Ифриты" },
            { "blackknight", "Рыцари тьмы" },
            { "reptiloidup", "Никсы-воины" },
            { "plant", "Хищные растения" },
            { "manticoreup", "Скорпикоры" },
            { "zpirate", "Пираты-зомби" },
            { "gatekeeper", "Стражи поднебесья" },
            { "smaster", "Мастера клинка" },
            { "fatpirateup", "Одноглазые пираты" },
            { "tenguup", "Ямабуси Тэнгу" },
            { "manticore", "Мантикоры" },
            { "pushkar", "Утопшие канониры" },
            { "cbal", "Мобильные баллисты" },
            { "valkyrie", "Валькирии" },
            { "krokodilup", "Стражи оазисов" },
            { "zasad", "Засадники" },
            { "thiefmage", "Воры-колдуны" },
            { "exile", "Маги-изгнанники" },
            { "wendigoup", "Древние вендиго" },
            { "assida", "Ассиды" },
            { "shootpirateup", "Флибустьеры" },
            { "diamondgolem", "Алмазные големы" },
            { "bigspider", "Гигантские пауки" },
            { "snowwolf", "Снежные волки" },
            { "spegasus", "Серебряные пегасы" },
            { "medusaup", "Медузы королевы" },
            { "sekhmet", "Сехметиты" },
            { "kachok", "Силачи" },
            { "acrossbowman", "Элитные арбалетчики" },
            { "cursed", "Ведьмы-призраки" },
            { "harpyhag", "Гарпии-ведьмы" },
            { "gnollboss", "Гноллы-вожаки" },
            { "warden", "Надзиратели" },
            { "crusader", "Крестоносцы" },
            { "priestess", "Жрицы моря" },
            { "fatpirate", "Толстяки" },
            { "tengu", "Тэнгу" },
            { "water", "Водные элементали" },
            { "fire", "Огненные элементали" },
            { "gnollsh", "Гноллы-шаманы" },
            { "thiefarcher", "Воры-убийцы" },
            { "krokodil", "Служители оазисов" },
            { "earth", "Земные элементали" },
            { "battlegriffin", "Боевые грифоны" },
            { "leprekon", "Лепреконы" },
            { "blackwidow", "Черные вдовы" },
            { "ocean", "Духи океана" },
            { "shootpirate", "Буканиры" },
            { "thiefwarrior", "Воры-разведчики" },
            { "air", "Воздушные элементали" },
            { "kamnegryz", "Камнегрызы" },
            { "vulture", "Пустынные налетчики" },
            { "medusa", "Медузы" },
            { "satyr", "Сатиры" },
            { "outlawup", "Чародеи-ренегаты" },
            { "piratkaup", "Корсарки" },
            { "pegasus", "Пегасы" },
            { "mercfootman", "Воины-наёмники" },
            { "harpy", "Гарпии" },
            { "nomad", "Кочевники" },
            { "ancientpig", "Древние кабаны" },
            { "negro", "Матросы-чужеземцы" },
            { "bpirate", "Абордажники" },
            { "spiderpois", "Ядовитые пауки" },
            { "apirate", "Корсары" },
            { "gnollum", "Метатели боласов" },
            { "banditka", "Лазутчицы" },
            { "robberup", "Соглядатаи" },
            { "skeletonpirateup", "Скелеты-корсары" },
            { "gnollka", "Дочери стаи" },
            { "cpirate", "Скелеты-моряки" },
            { "skeletonpirate", "Скелеты-пираты" },
            { "reptiloid", "Никсы" },
            { "kamneed", "Камнееды" },
            { "verblud", "Угонщики верблюдов" },
            { "spearthrower", "Прибрежные налётчики" },
            { "mercarcher", "Стрелки-наёмники" },
            { "highwayman", "Вышибалы" },
            { "piratka", "Пиратки" },
            { "bear", "Медведи" },
            { "megogachi", "Магоги" },
            { "gnollup", "Яростные гноллы" },
            { "boar", "Кабаны" },
            { "spider", "Пауки" },
            { "gnoll", "Гноллы" },
            { "robber", "Дозорные" },
            { "enforcer", "Мятежники" },
            { "brigandup", "Душегубы" },
            { "troglodyteup", "Адские троглодиты" },
            { "outlaw", "Колдуны-ренегаты" },
            { "gogachi", "Гоги" },
            { "bobbit", "Лесные хоббиты" },
            { "gnomon", "Молотобойцы" },
            { "troglodyte", "Троглодиты" },
            { "brigand", "Рубаки" },
            { "archangel", "Архангелы" },
            { "seraph2", "Высшие ангелы" },
            { "zealot", "Адепты" },
            { "angel", "Ангелы" },
            { "inquisitor", "Инквизиторы" },
            { "champion", "Чемпионы" },
            { "pikeman", "Копейщики" },
            { "cavalier", "Рыцари" },
            { "priest", "Монахи" },
            { "battlegriffon", "Штурмовые грифоны" },
            { "impergriffin", "Имперские грифоны" },
            { "squire", "Латники" },
            { "vindicator", "Защитники веры" },
            { "griffon", "Грифоны" },
            { "crossman", "Стрелки" },
            { "marksman", "Арбалетчики" },
            { "footman", "Пехотинцы" },
            { "brute", "Головорезы" },
            { "conscript", "Ополченцы" },
            { "archer", "Лучники" },
            { "peasant", "Крестьяне" },
            { "ghostdragon", "Астральные драконы" },
            { "spectraldragon", "Призрачные драконы" },
            { "bonedragon", "Костяные драконы" },
            { "wraith", "Вестники смерти" },
            { "banshee", "Баньши" },
            { "masterlich", "Высшие личи" },
            { "archlich", "Архиличи" },
            { "vampireprince", "Князья вампиров" },
            { "vampirelord", "Высшие вампиры" },
            { "wight", "Умертвия" },
            { "lich", "Личи" },
            { "vampire", "Вампиры" },
            { "spectre", "Призраки" },
            { "poltergeist", "Духи" },
            { "sceletonwar", "Скелеты-воины" },
            { "plaguezombie", "Чумные зомби" },
            { "ghost", "Привидения" },
            { "rotzombie", "Гниющие зомби" },
            { "skeletonarcher", "Скелеты-лучники" },
            { "zombie", "Зомби" },
            { "skmarksman", "Скелеты-арбалетчики" },
            { "skeleton", "Скелеты" },
            { "stormtitan", "Титаны шторма" },
            { "titan", "Титаны" },
            { "colossus", "Колоссы" },
            { "rakshasa_kshatra", "Кшатрии ракшасы" },
            { "rakshasa_raja", "Раджи ракшас" },
            { "rakshasa_rani", "Принцессы ракшас" },
            { "djinn_sultan", "Джинны-султаны" },
            { "archmage", "Архимаги" },
            { "djinn_vizier", "Визири джиннов" },
            { "battlemage", "Боевые маги" },
            { "djinn", "Джинны" },
            { "steelgolem", "Стальные големы" },
            { "magneticgolem", "Магнитные големы" },
            { "mage", "Маги" },
            { "saboteurgremlin", "Гремлины-вредители" },
            { "iron_golem", "Железные големы" },
            { "elgargoly", "Стихийные горгульи" },
            { "obsgargoyle", "Обсидиановые горгульи" },
            { "mastergremlin", "Старшие гремлины" },
            { "stone_gargoyle", "Каменные горгульи" },
            { "gremlin", "Гремлины" },
            { "crystaldragon", "Кристальные драконы" },
            { "emeralddragon", "Изумрудные драконы" },
            { "greendragon", "Зелёные драконы" },
            { "ancienent", "Древние энты" },
            { "savageent", "Дикие энты" },
            { "treant", "Энты" },
            { "pristineunicorn", "Светлые единороги" },
            { "silverunicorn", "Боевые единороги" },
            { "druideld", "Верховные друиды" },
            { "ddhigh", "Старшие друиды" },
            { "unicorn", "Единороги" },
            { "arcaneelf", "Лесные снайперы" },
            { "masterhunter", "Мастера лука" },
            { "druid", "Друиды" },
            { "elf", "Эльфийские лучники" },
            { "wdancer", "Танцующие с ветром" },
            { "wardancer", "Танцующие со смертью" },
            { "sprite", "Дриады" },
            { "dryad", "Нимфы" },
            { "dancer", "Танцующие с клинками" },
            { "pixel", "Феи" },
            { "cursedbehemoth", "Проклятые бегемоты" },
            { "ancientbehemoth", "Древние бегемоты" },
            { "dbehemoth", "Свирепые бегемоты" },
            { "shamancyclop", "Циклопы-шаманы" },
            { "behemoth", "Бегемоты" },
            { "cyclopod", "Циклопы-генералы" },
            { "cyclopking", "Циклопы-короли" },
            { "firebird", "Огненные птицы" },
            { "thunderbird", "Птицы грома" },
            { "darkbird", "Птицы тьмы" },
            { "cyclop", "Циклопы" },
            { "ogremagi", "Огры-маги" },
            { "ogreshaman", "Огры-шаманы" },
            { "orcshaman", "Орки-шаманы" },
            { "rocbird", "Роки" },
            { "ogrebrutal", "Огры-ветераны" },
            { "orcchief", "Орки-вожди" },
            { "orcrubak", "Орки-тираны" },
            { "goblinmag", "Гоблины-маги" },
            { "ogre", "Огры" },
            { "orc", "Орки" },
            { "boarrider", "Наездники на кабанах" },
            { "hyenarider", "Наездники на гиенах" },
            { "wolfraider", "Налётчики на волках" },
            { "goblinarcher", "Гоблины-лучники" },
            { "hobgoblin", "Хобгоблины" },
            { "wolfrider", "Наездники на волках" },
            { "goblin", "Гоблины" },
            { "reddragon", "Красные драконы" },
            { "blackdragon", "Чёрные драконы" },
            { "shadowdragon", "Сумеречные драконы" },
            { "mistress", "Хозяйки ночи" },
            { "matriarch", "Владычицы тени" },
            { "foulhydra", "Тёмные гидры" },
            { "deephydra", "Пещерные гидры" },
            { "taskmaster", "Минотавры-надсмотрщики" },
            { "shadow_witch", "Сумеречные ведьмы" },
            { "hydra", "Гидры" },
            { "briskrider", "Проворные наездники" },
            { "grimrider", "Тёмные всадники" },
            { "minotaurguard", "Минотавры-стражи" },
            { "darkrider", "Наездники на ящерах" },
            { "bloodsister", "Мегеры" },
            { "fury", "Фурии" },
            { "assassin", "Ассасины" },
            { "minotaur", "Минотавры" },
            { "stalker", "Ловчие" },
            { "maiden", "Бестии" },
            { "scout", "Лазутчики" },
            { "archdemon", "Архидемоны" },
            { "archdevil", "Архидьяволы" },
            { "devil", "Дьяволы" },
            { "pity", "Пещерные отродья" },
            { "pitlord", "Пещерные владыки" },
            { "hellkon", "Кони преисподней" },
            { "nightmare", "Кошмары" },
            { "pitfiend", "Пещерные демоны" },
            { "seducer", "Искусительницы" },
            { "hellcharger", "Адские жеребцы" },
            { "succubusmis", "Демонессы" },
            { "cerberus", "Церберы" },
            { "hotdog", "Огненные гончие" },
            { "succubus", "Суккубы" },
            { "hellhound", "Адские псы" },
            { "jdemon", "Старшие демоны" },
            { "hornedoverseer", "Огненные демоны" },
            { "vermin", "Дьяволята" },
            { "familiar", "Черти" },
            { "horneddemon", "Рогатые демоны" },
            { "imp", "Бесы" },
            { "lavadragon", "Лавовые драконы" },
            { "magmadragon", "Магма драконы" },
            { "firedragon", "Огненные драконы" },
            { "thunderlord", "Громовержцы" },
            { "flamelord", "Ярлы" },
            { "runekeeper", "Жрецы пламени" },
            { "runepatriarch", "Старейшины рун" },
            { "armorgnom", "Воители гор" },
            { "thane", "Таны" },
            { "runepriest", "Жрецы рун" },
            { "whitebearrider", "Северные наездники" },
            { "battlerager", "Воины ярости" },
            { "blackbearrider", "Хозяева медведей" },
            { "throwgnom", "Метатели молота" },
            { "berserker", "Берсерки" },
            { "bearrider", "Наездники на медведях" },
            { "brawler", "Костоломы" },
            { "harpooner", "Гарпунеры" },
            { "skirmesher", "Мастера копья" },
            { "shieldguard", "Воители" },
            { "axegnom", "Громоглавы" },
            { "mountaingr", "Горные стражи" },
            { "spearwielder", "Метатели копья" },
            { "defender", "Защитники гор" },
            { "untamedcyc", "Свободные циклопы" },
            { "bloodeyecyc", "Кровоглазые циклопы" },
            { "cyclopus", "Степные циклопы" },
            { "poukai", "Безглазые виверны" },
            { "foulwyvern", "Тёмные виверны" },
            { "chieftain", "Вожаки" },
            { "executioner", "Палачи" },
            { "sdaughter", "Дочери неба" },
            { "wyvern", "Виверны" },
            { "eadaughter", "Дочери земли" },
            { "slayer", "Убийцы" },
            { "warmong", "Вармонгеры" },
            { "mauler", "Степные бойцы" },
            { "shamaness", "Шаманки" },
            { "goblinshaman", "Гоблины-шаманы" },
            { "mcentaur", "Боевые кентавры" },
            { "ncentaur", "Кочевые кентавры" },
            { "warrior", "Степные воины" },
            { "trapper", "Гоблины-трапперы" },
            { "fcentaur", "Кентавры" },
            { "goblinus", "Степные гоблины" },
            { "anubisup", "Воины Анубиса" },
            { "anubis", "Слуги Анубиса" },
            { "priestsun", "Жрицы солнца" },
            { "slonup", "Штурмовые слоны" },
            { "priestmoon", "Жрицы луны" },
            { "slon", "Боевые слоны" },
            { "dromadup", "Налетчики на верблюдах" },
            { "shakalup", "Шакалы-воины" },
            { "dromad", "Наездники на верблюдах" },
            { "shakal", "Шакалы" },
            { "duneraiderup", "Пустынные убийцы" },
            { "scorpup", "Черные скорпионы" },
            { "scarabup", "Священные скарабеи" },
            { "duneraider", "Пустынные рейдеры" },
            { "scorp", "Скорпионы" },
            { "scarab", "Скарабеи" }
        };

        public static string Map(string name)
        {
            return CreatureMap.ContainsKey(name) ? CreatureMap[name] : name;
        }
    }
}
